
// import React, { useRef } from 'react';
// import styles from './RecommendationsCard.module.css';
// import IconButton from '@mui/material/IconButton';
// import CloseIcon from '@mui/icons-material/Close';
// import ReactMarkdown from 'react-markdown';
// import html2pdf from 'html2pdf.js';
// import logo from '../../assets/linkeye_logo 1.png';

// const RecommendationsCard = ({ ip, data, onClose }) => {
//   const cardRef = useRef();
//   const cleanAnalysis = (data?.ai_analysis || '')
//   .replace(/[\u{1F300}-\u{1F6FF}]/gu, '')         
//   .replace(/^\s*[\r\n]/gm, '')                    
//   .replace(/\n{2,}/g, '\n\n')                      
//   .trim();

//   const graphs = data?.graphs || [];

//   const handlePDFDownload = () => {
//     if (!cardRef.current) return;

//     const timestamp = new Date().toISOString().replace(/[:.]/g, '-');

//     const buttonGroup = cardRef.current.querySelector(`.${styles.buttonGroup}`);
//     const closeButton = cardRef.current.querySelector(`.${styles.closeButton}`);
//     if (buttonGroup) buttonGroup.style.display = 'none';
//     if (closeButton) closeButton.style.display = 'none';

//     html2pdf()
//       .set({
//         margin: [0.3, 0.1, 0.3, 0.1],
//         filename: `${ip}_recommendation_${timestamp}.pdf`,
//         pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
//         html2canvas: {
//           scale: 2,
//           useCORS: true,
//           scrollY: 0,
//         },
//         jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' },
//       })
//       .from(cardRef.current)
//       .save()
//       .then(() => {
//         if (buttonGroup) buttonGroup.style.display = 'flex';
//         if (closeButton) closeButton.style.display = 'block';
//       });
//   };

//   return (
//     <div className={styles.card} ref={cardRef}>
//       {/* Header */}
//       <div className={styles.header}>
//       <img src={logo} alt="Logo" className={styles.logo} />
       
//         <h2 className={styles.title}>ISP Bandwidth Report</h2>
//         <IconButton className={styles.closeButton} onClick={onClose} size="small">
//           <CloseIcon />
//         </IconButton>
//       </div>

//       {/* IP Address */}
//       <p className={styles.ip}><strong>IP:</strong> {ip}</p>

//       {/* Markdown Analysis */}
//       <div className={styles.markdown}>
//         <ReactMarkdown>{cleanAnalysis}</ReactMarkdown>
//       </div>

//       {/* Graphs from base64 */}
//       {graphs.length > 0 && (
//         <div className={styles.graphsSection}>
//           <h4 className={styles.graphsTitle}>Traffic Graphs</h4>
//           <div className={styles.graphContainer}>
//             {graphs.map((graph, index) => (
//               <img
//                 key={index}
//                 src={`data:image/png;base64,${graph.base64}`}
//                 alt={`Graph ${index + 1}`}
//                 className={styles.graphImage}
//               />
//             ))}
//           </div>
//         </div>
//       )}

//       {/* Footer */}
//       <div className={styles.footer}>
//         Generated by AI Engine | © AI Team 2025
//       </div>

//       {/* Download Button */}
//       <div className={styles.buttonGroup}>
//         <button className={styles.button} onClick={handlePDFDownload}>
//           Download PDF Report
//         </button>
//       </div>
//     </div>
//   );
// };

// export default RecommendationsCard;


import React from 'react';
import styles from './RecommendationsCard.module.css';
import IconButton from '@mui/material/IconButton';
import CloseIcon from '@mui/icons-material/Close';
import logo from '../../assets/linkeye_logo 1.png';

const RecommendationsCard = ({ ip, pdfUrl, onClose }) => {
  const handlePDFDownload = () => {
    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = `${ip}_report.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className={styles.card}>
      {/* Header */}
      <div className={styles.header}>
        <img src={logo} alt="Logo" className={styles.logo} />
        <h2 className={styles.title}>ISP Bandwidth Report</h2>
        <IconButton className={styles.closeButton} onClick={onClose} size="small">
          <CloseIcon />
        </IconButton>
      </div>

      {/* IP Address */}
      <p className={styles.ip}><strong>IP:</strong> {ip}</p>

     
      <div className={styles.pdfPreview}>
        <p className={styles.note}>Your bandwidth report is ready. Click below to download the full PDF.</p>
      </div>

      {/* Footer */}
      <div className={styles.footer}>
        Generated by AI Engine | © AI Team 2025
      </div>

      {/* Button */}
      <div className={styles.buttonGroup}>
        <button className={styles.button} onClick={handlePDFDownload}>
          Download PDF Report
        </button>
      </div>
    </div>
  );
};

export default RecommendationsCard;
